### ISSUE TITLE
Is it possible to integrate this with Presta 1.7?

### ISSUE THREAD

**Issue by backamblock** [SLiCK-303/sendreviewrequest#7]
Hey there, is it possible to integrate this to presta 1.7?
i uploaded the module to my testshop with no problems, everything shows correct in the modules sectiojn.
but when i go to the link mentioned as cron i only get an error.
what happened here?

Another thing is the checkbox. i can set a text in the gdpr module but it does not show anywhere in the checkout? How does the module know if a user accepted the "send a review email" thingi?

greetings

**Comment by SLiCK-303** [comment]
i do not code my modules to be compliant to PrestaShop, only Thirtybees.  If you can get it to work the more power to ya!
